### ISSUE TITLE
Css system doesn't work

### ISSUE THREAD

**Issue by manfrombar** [rcvd/roam-css-system#50] opened 2021-08-10 06:15 UTC
Hello, since yesterday the css-system and Things Theme it doesn't works. I am wondering if is it happening only to be? In my case suddenly stopped to work.
Thnaks again for your help.

![CleanShot 2021-08-10 at 08 14 08](https://user-images.githubusercontent.com/16494529/128817257-dedac055-5cc2-4596-8fad-ce8896cebe98.png)

**Comment by rcvd** [comment] 2021-08-10 06:20
No problems on my site. Maybe one of your overwrite blocks is missing a closing bracket? Try moving your overwrite block to another page, check if the theme works again, re-add them step by step. Have you identified the problem?

Sometimes this can also be caused by plugins - don't know if you are using some.

**Comment by manfrombar** [comment] 2021-08-10 07:03
I have some plugins, but nothing new. 
I have tried deleting the overwritten part. But no works. Also, all code is now in Plain Text.
The frustrating thing I am not conscious of doing anything. Just stop working.
Probably will be a silly thing. But I am completely lost.

![CleanShot 2021-08-10 at 09 01 45](https://user-images.githubusercontent.com/16494529/128822768-9f60d429-5016-4dbf-84ad-df9a794d538f.png)

**Comment by manfrombar** [comment] 2021-08-10 07:15
Ok. I got it. I have no idea why.
I have included {{roam/css}} and start working again.
As all code is on roam/CSS page I didn't include it. And was working perfectly. I don't understand.

![CleanShot 2021-08-10 at 09 08 32](https://user-images.githubusercontent.com/16494529/128823950-7015f416-bcc8-434e-8cdf-372b626bc2e0.png)

**Comment by itsjustmath** [comment] 2021-08-10 22:02
@manfrombar If styles aren't being applied, its likely because you need to move any `@import` to the top of `roam/css` (above any custom [longhand] CSS you've written)

**Closed** 2021-08-20 18:32 UTC
